function myMainScriptGUI

close all;


sz = [300 800]; % figure size
screenSize = get(0,'ScreenSize');
xPos = ceil((screenSize(3)-sz(2))/2); % center the figure on the screen horizontally
yPos = ceil((screenSize(4)-sz(1))/2); % center the figure on the screen vertically
f = figure(...
		'position',[xPos, yPos, sz(2), sz(1)+22],...
		'units','pixels',...
		'MenuBar','none',...
		'color', [0.7 0.7 0.7],...
		'PaperPositionMode','auto',...
		'Name','Real-Time Object Tracking',...
		'NumberTitle','off',...
		'Tag','gui',...
		'Resize','on');
videoSelectButton = uicontrol('Style','pushbutton',...
					'String','Select a video file', ...
					'Position',[315,220,70,25]);
selectObjButton = uicontrol('Style','pushbutton',...
				'String','Select the object to track',...
				'Position',[315,180,70,25]);
runAlgoButton = uicontrol('Style','pushbutton',...
				'String','Run the algorithm',...
				'Position',[315,135,70,25]);
set(f,'Visible','on');
videoFilePath = '';

function openVideoFile(hObject, calleventdata, i, j, row, col, figureHandle)


end


end